#!/usr/bin/env python
import random
import sys
sys.path.append("modules/")
# import atlas styles
from AtlasStyle import *
from AtlasUtils import *
from ROOT import *
from array import *
from math import *
import math

lumi=32900# 24799.9 MD3#18900.0 MD2#10064.3+3212.96  #5644.58+3193.68  #10064.3+3212.96 #3212.96 #5644.58 # 2613.83 #3193.68 #DE:199.5#D:80.359#dijet 3234
Lumi=" %.1f fb^{-1}" % (lumi/1000.)
lumi_2016=32900  #2613.83
Lumi_2016=" %.1f fb^{-1}" % (lumi_2016/1000.)
intLUMI="#int L dt = "+Lumi
CME="#sqrt{s} = 13 TeV"
CMELUMI="#sqrt{s} = 13 TeV, "+ Lumi #+"/"+Lumi_2016
CMELUMI_2016="#sqrt{s} = 13 TeV, "+Lumi_2016
#CMELUMI="#sqrt{s} = 13 TeV, run 283608"
AtlasLabel="Internal"
IncluLabel="Inclusive"
IncluOneBLabel="#geq1 b-tag (1st,2nd)"
ExcluOneBLabel="1 b-tag (1st,2nd)"
ExcluTwoBLabel="2 b-tag (1st,2nd)"
IncluOneProbeBLabel="#geq1 b-tag (3rd,4th)"
ExcluOneProbeBLabel="1 b-tag (3rd,4th)"
IncluTwoProbeBLabel="2 b-tag (3rd,4th)"

qcdSamples = [
    #"JZ0W",
    #"JZ1W",
    #"JZ2W",
    "JZ3W",
    "JZ4W",
    "JZ5W",
    "JZ6W",
    "JZ7W",
    "JZ8W",
    "JZ9W",
    "JZ10W",
    "JZ11W",
    "JZ12W",
]

crossSections = {
    "JZ0W" : 7842.0E+07*0.98132+00,
    "JZ1W" : 7842.0E+07*6.7198E-04,
    "JZ2W" : 2433.4E+06*3.3264E-04,
    "JZ3W" : 2645.4E+04*3.1953E-04,
    "JZ4W" : 2546.4E+02*5.3009E-04,
    "JZ5W" : 4553.6E+00*9.2325E-04,
    "JZ6W" : 2575.2E-01*9.4016E-04,
    "JZ7W" : 1621.4E-02*3.9282E-04,
    "JZ8W" : 6250.5E-04*1.0162E-02,
    "JZ9W" : 1964.0E-05*1.2054E-02,
    "JZ10W" : 119.62E-05*5.897E-03,
    "JZ11W" : 4.226E-05*2.701E-03,
    "JZ12W" : 1.037E-06*0.425E-02,
    "QCD"       : -1,
}    

sampleLocations = {"pythiadir" : "/users/bingxuan.liu/FourBFramework/analysis/out/Pythia8_AllChannels/sys0/"}
outputPath = "./test.root"

colors = {
    "JZ0W" : 1,
    "JZ1W" : 2,
    "JZ2W" : 3,
    "JZ3W" : 6,
    "JZ4W" : 8,
    "JZ5W" : 9,
    "JZ6W" : 12,
    "JZ7W" : 11,
    "JZ8W" : 46,
    "JZ9W" : 39,
    "JZ10W": 49,
    "JZ11W": 59,
    "JZ12W": 69,
}  

histograms = {
    "FirstJetPt" : {
        "logy"    :   1,
        "name"    :   "pt_1",
        "nameX"   :   "p_{T}^{1st} [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   4000,
    },
    "SecondJetPt" : {
        "logy"    :   1,
        "name"    :   "pt_2",
        "nameX"   :   "p_{T}^{2nd} [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   4000,
    },
    "ThirdJetPt" : {
        "logy"    :   1,
        "name"    :   "pt_3",
        "nameX"   :   "p_{T}^{3rd} [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   4000,
    },
    "FourthJetPt" : {
        "logy"    :   1,
        "name"    :   "pt_4",
        "nameX"   :   "p_{T}^{4th} [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   4000,
    },
    "FirstJetEta" : {
        "logy"    :   1,
        "name"    :   "eta_1",
        "nameX"   :   "#eta^{1st}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -5,
        "Xmax"    :   5,
    },
    "SecondJetEta" : {
        "logy"    :   1,
        "name"    :   "eta_2",
        "nameX"   :   "#eta^{2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -5,
        "Xmax"    :   5,
    },
    "ThirdJetEta" : {
        "logy"    :   1,
        "name"    :   "eta_3",
        "nameX"   :   "#eta^{3rd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -5,
        "Xmax"    :   5,
    },
    "FourthJetEta" : {
        "logy"    :   1,
        "name"    :   "eta_4",
        "nameX"   :   "#eta^{4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -5,
        "Xmax"    :   5,
    },
    "FirstJetPhi" : {
        "logy"    :   1,
        "name"    :   "phi_1",
        "nameX"   :   "#phi^{1st}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -3.2,
        "Xmax"    :   3.2,
    },
    "SecondJetPhi" : {
        "logy"    :   1,
        "name"    :   "phi_2",
        "nameX"   :   "#phi^{2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -3.2,
        "Xmax"    :   3.2,
    },
    "ThirdJetPhi" : {
        "logy"    :   1,
        "name"    :   "phi_3",
        "nameX"   :   "#phi^{3rd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -3.2,
        "Xmax"    :   3.2,
    },
    "FourthJetPhi" : {
        "logy"    :   1,
        "name"    :   "phi_4",
        "nameX"   :   "#phi^{4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -3.2,
        "Xmax"    :   3.2,
    },
    "FirstJetMV2c10" : {
        "logy"    :   1,
        "name"    :   "mv2c10_1",
        "nameX"   :   "MC2c10^{1st} Score",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -3.2,
        "Xmax"    :   3.2,
    },
    "SecondJetMV2c10" : {
        "logy"    :   1,
        "name"    :   "mv2c10_2",
        "nameX"   :   "MV2c10^{2nd} Score",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -3.2,
        "Xmax"    :   3.2,
    },
    "ThirdJetMV2c10" : {
        "logy"    :   1,
        "name"    :   "mv2c10_3",
        "nameX"   :   "MV2c10^{3rd} Score",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -3.2,
        "Xmax"    :   3.2,
    },
    "FourthJetMV2c10" : {
        "logy"    :   1,
        "name"    :   "mv2c10_4",
        "nameX"   :   "MV2c10^{4th} Score",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -3.2,
        "Xmax"    :   3.2,
    },
    "FirstJetTruthId" : {
        "logy"    :   1,
        "name"    :   "truthId_1",
        "nameX"   :   "Truth 1st Jet Id",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   25,
    },
    "SecondJetTruthId" : {
        "logy"    :   1,
        "name"    :   "truthId_2",
        "nameX"   :   "Truth 2nd Jet Id",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   25,
    },
    "ThirdJetTruthId" : {
        "logy"    :   1,
        "name"    :   "truthId_3",
        "nameX"   :   "Truth 3rd Jet Id",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   25,
    },
    "FourthJetTruthId" : {
        "logy"    :   1,
        "name"    :   "truthId_4",
        "nameX"   :   "Truth 4th Jet Id",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   25,
    },
    "FirstSecondJetInvMass" : {
        "logy"    :   1,
        "name"    :   "mjj_12",
        "nameX"   :   "M_{1st,2nd} [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   8000,
    },
    "ThirdFourthJetInvMass" : {
        "logy"    :   1,
        "name"    :   "mjj_34",
        "nameX"   :   "M_{3rd,4th} [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   8000,
    },
    "FirstSecondJetyStar" : {
        "logy"    :   1,
        "name"    :   "ystar_12",
        "nameX"   :   "y^{*}_{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -5,
        "Xmax"    :   5,
    },
    "ThirdFourthJetyStar" : {
        "logy"    :   1,
        "name"    :   "ystar_34",
        "nameX"   :   "y^{*}_{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -5,
        "Xmax"    :   5,
    },
    "FirstSecondJetdEta" : {
        "logy"    :   1,
        "name"    :   "deta_12",
        "nameX"   :   "#Delta#eta_{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   5,
    },
    "ThirdFourthJetdEta" : {
        "logy"    :   1,
        "name"    :   "deta_34",
        "nameX"   :   "#Delta#eta_{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   5,
    },
    "FirstSecondJetdPhi" : {
        "logy"    :   1,
        "name"    :   "dphi_12",
        "nameX"   :   "#Delta#phi_{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "ThirdFourthJetdPhi" : {
        "logy"    :   1,
        "name"    :   "dphi_34",
        "nameX"   :   "#Delta#phi_{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "FirstSecondJetdR" : {
        "logy"    :   1,
        "name"    :   "dR_12",
        "nameX"   :   "#DeltaR_{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "ThirdFourthJetdR" : {
        "logy"    :   1,
        "name"    :   "dR_34",
        "nameX"   :   "#DeltaR_{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "FirstSecondJetmBoost" : {
        "logy"    :   1,
        "name"    :   "mboost_12",
        "nameX"   :   "M^{boost}_{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   7500,
    },
    "ThirdFourthJetmBoost" : {
        "logy"    :   1,
        "name"    :   "mboost_34",
        "nameX"   :   "M^{boost}_{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   7500,
    },
    "FirstSecondJettheta" : {
        "logy"    :   1,
        "name"    :   "theta_12",
        "nameX"   :   "#Theta_{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "ThirdFourthJettheta" : {
        "logy"    :   1,
        "name"    :   "theta_34",
        "nameX"   :   "#Theta_{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "FirstSecondJetangle" : {
        "logy"    :   1,
        "name"    :   "angle_12",
        "nameX"   :   "Angle_{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "ThirdFourthJetangle" : {
        "logy"    :   1,
        "name"    :   "angle_34",
        "nameX"   :   "Angle_{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "FirstSecondJettheta" : {
        "logy"    :   1,
        "name"    :   "theta_12",
        "nameX"   :   "#Theta_{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "ThirdFourthJettheta" : {
        "logy"    :   1,
        "name"    :   "theta_34",
        "nameX"   :   "#Theta_{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   3.2,
    },
    "FirstSecondJetdPt" : {
        "logy"    :   1,
        "name"    :   "deltaPt_12",
        "nameX"   :   "#Deltap_{T}^{1st,2nd}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   1000,
    },
    "ThirdFourthJetdPt" : {
        "logy"    :   1,
        "name"    :   "deltaPt_34",
        "nameX"   :   "#Deltap_{T}^{3rd,4th}",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   1000,
    },
    "FirstSecondJetdMass" : {
        "logy"    :   1,
        "name"    :   "deltaMass_12",
        "nameX"   :   "M_{1st,2nd} - M^{boost}_{1st,2nd}, [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -2000,
        "Xmax"    :   2000,
    },
    "ThirdFourthJetdMass" : {
        "logy"    :   1,
        "name"    :   "deltaMass_34",
        "nameX"   :   "M_{3rd,4th} - M^{boost}_{3rd,4th}, [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   -2000,
        "Xmax"    :   2000,
    },
    "FirstSecondJetsumPVec" : {
        "logy"    :   1,
        "name"    :   "sumPVec_12",
        "nameX"   :   "|#vec{P}_{1st} + #vec{P}_{2nd}|, [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   8000,
    },
    "ThirdFourthJetsumPVec" : {
        "logy"    :   1,
        "name"    :   "sumPVec_34",
        "nameX"   :   "|#vec{P}_{3rd} + #vec{P}_{4th}|, [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   8000,
    },
    "FirstSecondJetsumPtVec" : {
        "logy"    :   1,
        "name"    :   "sumPtVec_12",
        "nameX"   :   "|#vec{p_{T}}^{1st} + #vec{p_{T}}^{2nd}|, [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   8000,
    },
    "ThirdFourthJetsumPtVec" : {
        "logy"    :   1,
        "name"    :   "sumPtVec_34",
        "nameX"   :   "|#vec{p_{T}}^{3rd} + #vec{p_{T}}^{4th}|, [GeV]",
        "nameY"   :   "Event",
        "Ymin"    :   0.05,
        "Ymax"    :   5e8,
        "Xmin"    :   0,
        "Xmax"    :   8000,
    },
}

categories = {
    "Inclusive" : {
        "name"  : "Inclusive",
        "label" : IncluLabel,
    },
    "InclusiveOneB" : {
        "name"  : "InclusiveOneB",
        "label" : IncluOneBLabel,
    },
    "ExclusiveOneB" : {
        "name"  : "ExclusiveOneB",
        "label" : ExcluOneBLabel,
    },
    "ExclusiveTwoB" : {
        "name"  : "ExclusiveTwoB",
        "label" : ExcluTwoBLabel,
    },
    "InclusiveOneProbeB" : {
        "name"  : "InclusiveOneProbeB",
        "label" : IncluOneProbeBLabel,
    },
    "ExclusiveOneProbeB" : {
        "name"  : "ExclusiveOneProbeB",
        "label" : ExcluOneProbeBLabel,
    },
    "InclusiveTwoProbeB" : {
        "name"  : "InclusiveTwoProbeB",
        "label" : IncluTwoProbeBLabel,
    },
}
